### ISSUE TITLE
Migration of Daylight Savings Time code from NTPtimeESP

### ISSUE THREAD

**Issue by sirtuxalot** [SensorsIot/SNTPtime#3]
Sir,
Thank you for your work on this library.  I am using it to create a WiFi Binary Clock.  I was initially going to use your NTPtimeESP library for this, but sending regular NTP requests for seemed a bit excessive for this project.  I can confirm the ticket created by retep ans I had the same issues and correcting the case of the library name resolved the issue.

As my subject requests, I was hoping you would migrate the code that handles the US Daylight Savings from the NTPtimeESP library to this library (SNTPtime).

**Comment by SensorsIot** [comment]
This is an old project. Maybe somebody else does it and creates a pull request?
