### ISSUE TITLE
Code fix for US change to/from Daylight Savings Time

### ISSUE THREAD

**Issue by sirtuxalot** [SensorsIot/SNTPtime#4]
My implementation on the automatic changing to/from daylight savings time.  I am by no means a C++ developer...yet, but this is what I have running in a project I am working on.

Replace lines 117-118
`
  if (_tempDateTime.month < 3 || _tempDateTime.month > 11) return false;
  if (_tempDateTime.month > 3 && _tempDateTime.month < 11) return true;
  int previousSunday = _tempDateTime.day - (_tempDateTime.dayofWeek - 1);
  if (_tempDateTime.month == 3 ) {
    if ( previousSunday >= 8 ) {
      return ((_tempDateTime.day > 14) || 
      ((_tempDateTime.dayofWeek == 1 && _tempDateTime.hour >= 2) || _tempDateTime.dayofWeek > 1));
    }
    else
    {
      return false;
    } 
  }
  if (previousSunday < 1)
  {
    return ((_tempDateTime.dayofWeek == 1 && _tempDateTime.hour < 2) || (_tempDateTime.dayofWeek > 1));
  }
  else
  {
    return (_tempDateTime.day <8 && _tempDateTime.dayofWeek == 1 && _tempDateTime.hour < 2);
  }
`
Sorry, not a pro with git either so I just added code to comment.

**Comment by SensorsIot** [comment]
Thank you for your addition!
