### ISSUE TITLE
Warnings on compilation

### ISSUE THREAD

**Issue by consolacion** [SensorsIot/SNTPtime#6]
error/warnings
lately I am getting 'warnings'  on compilation:
33 | SNTPtime NTPch("ch.pool.ntp.org");
      |                ^~~~~~~~~~~~~~~~~
/home/user/Arduino/libraries/SNTPtime-master/SNTP.cpp:41:18: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   41 | char *_NTPserver="";
   
   It will still work, but seems something has changed in the library

**Comment by consolacion** [comment]
Lost the  first  warning in copy paste:  below  the 2 warnings complete:

/home/user/Arduino/sntptime/sntptime.ino:33:16: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   33 | SNTPtime NTPch("ch.pool.ntp.org");
      |                ^~~~~~~~~~~~~~~~~
/home/user/Arduino/libraries/SNTPtime-master/SNTP.cpp:41:18: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]
   41 | char *_NTPserver="";
      |

**Comment by SensorsIot** [comment]
This is only a warning. I would not pay attention to it if it works.
